version: '3.8'
services:
  db:
    image: mvertes/alpine-mongo
    container_name: "mongodb_container"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - "./docker/mongodb-local/db:/data/db"
    ports:
      - "27017:27017"
    restart: unless-stopped